# Generated by Django 5.1.3 on 2024-11-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rels', '0002_alter_realstate_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='rels_image'),
        ),
    ]
